accelerate launch src/textual_inversion.py \
  --pretrained_model_name_or_path /apdcephfs_cq10/share_916081/jentsehuang/models/stable-diffusion-2-1-base \
  --train_data_dir /apdcephfs_cq8/share_916081/jentsehuang/textual_inversion/input/starry_night \
  --resolution=512 \
  --learning_rate=5.0e-04 \
  --seed=3467 \
  --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --learnable_property="object" \
  --placeholder_token="<object>" \
  --initializer_token="object" \
  --train_batch_size 4 \
  --gradient_accumulation_steps 1 \
  --max_train_steps 1000 \
  --checkpointing_steps 5000 \
  --output_dir /apdcephfs_cq8/share_916081/jentsehuang/textual_inversion/output/full/baseline/starry_night
  --distilled_ckpt /apdcephfs_cq10/share_916081/jentsehuang/TI_distill/sd_2_1/$MODEL_ID/HS_GM_mse_diff_loss_ablation/ckpts/checkpoint-35000/model_ckpt.pt
